In [11]:
import pandas as pd
import matplotlib.pyplot as plt
from unidecode import unidecode

In [12]:
df = pd.read_csv("incidencia_00.csv", encoding='ISO-8859-1')
df.head()

,cve_entidad,desc_entidad,cve_municipio,desc_municipio,id_indicador,indicador,2010,2011,2012,2013,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,unidad_medida
0,0,Estados Unidos Mexicanos,0,Estados Unidos Mexicanos,6200002201,Porcentaje de unidades económicas víctimas del...,NaN,37.365920,NaN,33.634243,...,35.484960,NaN,33.732887,NaN,30.462028,NaN,24.629802,NaN,NaN,Porcentaje
1,0,Estados Unidos Mexicanos,0,Estados Unidos Mexicanos,6200002231,Cifra negra de delitos en unidades económicas,NaN,88.122608,NaN,88.054676,...,90.347165,NaN,86.562996,NaN,92.016873,NaN,91.541154,NaN,NaN,Porcentaje
2,0,Estados Unidos Mexicanos,0,Estados Unidos Mexicanos,6200002234,Porcentaje de delitos con portación de armas e...,NaN,45.480340,NaN,45.301208,...,34.728797,NaN,47.683472,NaN,31.042686,NaN,33.581976,NaN,NaN,Porcentaje
3,0,Estados Unidos Mexicanos,0,Estados Unidos Mexicanos,6200005814,Porcentaje de delitos con portación de armas e...,40.674462,48.445682,44.142811,50.225366,...,45.212453,43.06050,44.210583,45.596156,42.850759,41.550866,38.087719,35.546679,34.166877,Porcentaje
4,0,Estados Unidos Mexicanos,0,Estados Unidos Mexicanos,6200005821,Cifra Negra (delitos no denunciados y los deli...,91.985651,91.619014,92.091139,93.803162,...,93.714687,93.64847,93.237094,93.237497,92.392142,93.269372,93.212103,92.443486,92.912121,Porcentaje

In [18]:
print(df.columns)

Index(['cve_entidad', 'desc_entidad', 'cve_municipio', 'desc_municipio',
       'id_indicador', 'indicador', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       'unidad_medida'],
      dtype='object')

In [21]:
FILTRO = ((df['indicador'] == "Porcentaje de delitos con portacion de armas en personas de 18 años y mas") & (df['desc_entidad'] == "Aguascalientes" ) & (df['2020']))
COLUMNAS = ['desc_entidad', 'indicador', '2020']
df[FILTRO][COLUMNAS]

Empty DataFrame
Columns: [desc_entidad, indicador, 2020]
Index: []

In [22]:
FILTRO = ((df['indicador'] == "Cifra negra de delitos en unidades econmicas") & (df['desc_entidad'] == "Baja California" ) & (df['2021']))
COLUMNAS = ['desc_entidad', 'indicador', '2021']
df[FILTRO][COLUMNAS]

Empty DataFrame
Columns: [desc_entidad, indicador, 2021]
Index: []

In [ ]:
FILTRO= ((df['indicador'] == "Porcentaje de hogares vctimas del delito") & (df['desc_entidad'] == "Campeche" ) & (df['2022']))
COLUMNAS = ['desc_entidad', 'indicador', '2022']
df[FILTRO][COLUMNAS]

Empty DataFrame
Columns: [desc_entidad, indicador, 2022]
Index: []

In [23]:
FILTRO = ((df["unidad_medida"] == "Tasa"))
COLUMNAS = ['desc_entidad','indicador','unidad_medida']
df[FILTRO][COLUMNAS]

,desc_entidad,indicador,unidad_medida
9,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
10,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
11,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
12,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
13,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
14,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
15,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
16,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
17,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
18,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
23,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
24,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
25,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
26,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
28,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
29,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
30,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
43,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Tasa
57,Aguascalientes,Porcentaje de hogares víctimas del delito,Tasa
71,Baja California,Porcentaje de hogares víctimas del delito,Tasa
85,Baja California Sur,Porcentaje de hogares víctimas del delito,Tasa
99,Campeche,Porcentaje de hogares víctimas del delito,Tasa
113,Coahuila de Zaragoza,Porcentaje de hogares víctimas del delito,Tasa
127,Colima,Porcentaje de hogares víctimas del delito,Tasa
141,Chiapas,Porcentaje de hogares víctimas del delito,Tasa
155,Chihuahua,Porcentaje de hogares víctimas del delito,Tasa
169,Ciudad de México,Porcentaje de hogares víctimas del delito,Tasa
183,Durango,Porcentaje de hogares víctimas del delito,Tasa
197,Guanajuato,Porcentaje de hogares víctimas del delito,Tasa
211,Guerrero,Porcentaje de hogares víctimas del delito,Tasa
225,Hidalgo,Porcentaje de hogares víctimas del delito,Tasa
239,Jalisco,Porcentaje de hogares víctimas del delito,Tasa
253,México,Porcentaje de hogares víctimas del delito,Tasa
267,Michoacán de Ocampo,Porcentaje de hogares víctimas del delito,Tasa
281,Morelos,Porcentaje de hogares víctimas del delito,Tasa
295,Nayarit,Porcentaje de hogares víctimas del delito,Tasa
309,Nuevo León,Porcentaje de hogares víctimas del delito,Tasa
323,Oaxaca,Porcentaje de hogares víctimas del delito,Tasa
337,Puebla,Porcentaje de hogares víctimas del delito,Tasa
351,Querétaro,Porcentaje de hogares víctimas del delito,Tasa
365,Quintana Roo,Porcentaje de hogares víctimas del delito,Tasa
379,San Luis Potosí,Porcentaje de hogares víctimas del delito,Tasa
393,Sinaloa,Porcentaje de hogares víctimas del delito,Tasa
407,Sonora,Porcentaje de hogares víctimas del delito,Tasa
421,Tabasco,Porcentaje de hogares víctimas del delito,Tasa
435,Tamaulipas,Porcentaje de hogares víctimas del delito,Tasa
449,Tlaxcala,Porcentaje de hogares víctimas del delito,Tasa
463,Veracruz de Ignacio de la Llave,Porcentaje de hogares víctimas del delito,Tasa
477,Yucatán,Porcentaje de hogares víctimas del delito,Tasa
491,Zacatecas,Porcentaje de hogares víctimas del delito,Tasa
495,Zacatecas,Porcentaje de hogares víctimas del delito,Tasa

In [24]:
FILTRO= ((df["unidad_medida"] == "Porcentaje"))
COLUMNAS = ['desc_entidad','indicador','unidad_medida']
df[FILTRO][COLUMNAS]

,desc_entidad,indicador,unidad_medida
0,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Porcentaje
1,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Porcentaje
2,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Porcentaje
3,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Porcentaje
4,Estados Unidos Mexicanos,Porcentaje de hogares víctimas del delito,Porcentaje
...,...,...,...
482,Zacatecas,Porcentaje de hogares víctimas del delito,Porcentaje
483,Zacatecas,Porcentaje de hogares víctimas del delito,Porcentaje
484,Zacatecas,Porcentaje de hogares víctimas del delito,Porcentaje
485,Zacatecas,Porcentaje de hogares víctimas del delito,Porcentaje
486,Zacatecas,Porcentaje de hogares víctimas del delito,Porcentaje

In [25]:
years = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
COLS = ['desc_entidad', 'indicador'] + [str(year) for year in years]

FILTRO = (
    (df['indicador'] == "Porcentaje de delitos con portacin de armas en personas de 18 aos y ms") &
    (df['desc_entidad'] == "Aguascalientes")
)
filtered_df = df[FILTRO][COLUMNAS]

if not filtered_df.empty:
    
    plt.figure(figsize=(10, 6))
    for index, row in filtered_df.iterrows():
        plt.plot(years, row[2:], marker='o')

    plt.xlabel('Años')
    plt.ylabel('Porcentaje')
    plt.title('Porcentaje de delitos con portación de armas en Aguascalientes')
    plt.legend()
    plt.grid(True)
    plt.show()
    print(df[FILTRO][COLUMNAS])
else:
    print("No se encuentran datos.")

No se encuentran datos.