In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('Gover_exp_Rev_euro.csv')

data.tail()

,"freq,unit,sector,na_item,geo\TIME_PERIOD",1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
53299,"A,PC_GDP,S212,D2REC,PT",0.2,0.2,0.2,0.2,0.2,0.2,0.1,0.1,0.1,...,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.1,0.1
53300,"A,PC_GDP,S212,D2REC,RO",: m,: m,: m,: m,: m,: m,: m,: m,: m,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
53301,"A,PC_GDP,S212,D2REC,SE",0.2,0.2,0.2,0.2,0.2,0.2,0.1,0.1,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,0.2,0.1,0.1,0.1
53302,"A,PC_GDP,S212,D2REC,SI",: m,: m,: m,: m,: m,: m,: m,: m,: m,...,0.2,0.2,0.1,0.1,0.2,0.2,0.2,0.1,0.1,0.1
53303,"A,PC_GDP,S212,D2REC,SK",: m,: m,: m,: m,: m,: m,: m,: m,: m,...,0.2,0.2,0.2,0.2,0.1,0.2,0.2,0.1,0.1,0.1

In [4]:
#Separamos la primera columna en 5 columnas nuevas con .str.split
data[['freq', 'unit', 'sector', 'na_item', 'geo']] = data[r'freq,unit,sector,na_item,geo\TIME_PERIOD'].str.split(pat=',', expand=True)

#Reemplazar los textos nulos por valores nulos matematicos
data = data.replace(': m', np.nan)
data.head()

,"freq,unit,sector,na_item,geo\TIME_PERIOD",1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2021,2022,2023,2024,2025,freq,unit,sector,na_item,geo
0,"A,MIO_EUR,S1,D3REC_S212,AT",:,:,:,:,:,:,:,:,:,...,1087.7,1132.7,1025.0,1059.8,1067.8,A,MIO_EUR,S1,D3REC_S212,AT
1,"A,MIO_EUR,S1,D3REC_S212,BE",1068.5,864.6,824.2,738.1,857.6,694.2,733.6,710.6,865.8,...,653.9,690.8,703.6,690.6 p,690.6 p,A,MIO_EUR,S1,D3REC_S212,BE
2,"A,MIO_EUR,S1,D3REC_S212,BG",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1623.0,902.2,886.4,871.3,710.0,A,MIO_EUR,S1,D3REC_S212,BG
3,"A,MIO_EUR,S1,D3REC_S212,CH",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,:,A,MIO_EUR,S1,D3REC_S212,CH
4,"A,MIO_EUR,S1,D3REC_S212,CY",:,:,:,:,:,:,:,:,:,...,70.3,68.7,36.3,54.5,91.2,A,MIO_EUR,S1,D3REC_S212,CY

In [5]:
# Eliminamos la primera columna que no necesitamos con .drop columns (usar .index para las filas horizontales)
data = data.drop(columns=(r'freq,unit,sector,na_item,geo\TIME_PERIOD'))

In [6]:
# Creamos la lista de años para limpiar los datos de los años de manera general
lista_de_años = data.loc[:, '1995':'2025'].columns 


data.head()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2021,2022,2023,2024,2025,freq,unit,sector,na_item,geo
0,:,:,:,:,:,:,:,:,:,1091.8,...,1087.7,1132.7,1025.0,1059.8,1067.8,A,MIO_EUR,S1,D3REC_S212,AT
1,1068.5,864.6,824.2,738.1,857.6,694.2,733.6,710.6,865.8,811.5,...,653.9,690.8,703.6,690.6 p,690.6 p,A,MIO_EUR,S1,D3REC_S212,BE
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1623.0,902.2,886.4,871.3,710.0,A,MIO_EUR,S1,D3REC_S212,BG
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,:,A,MIO_EUR,S1,D3REC_S212,CH
4,:,:,:,:,:,:,:,:,:,7.9,...,70.3,68.7,36.3,54.5,91.2,A,MIO_EUR,S1,D3REC_S212,CY

In [8]:
# Generalizamos los cambios con .apply
# Con .to_numeric creamos cualquier dato a numerico (con errors='coerce' le decimos que si encuentra un error no pare)
data[lista_de_años] = data[lista_de_años].apply(pd.to_numeric, errors='coerce')

data.head(5)

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2021,2022,2023,2024,2025,freq,unit,sector,na_item,geo
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1091.8,...,1087.7,1132.7,1025.0,1059.8,1067.8,A,MIO_EUR,S1,D3REC_S212,AT
1,1068.5,864.6,824.2,738.1,857.6,694.2,733.6,710.6,865.8,811.5,...,653.9,690.8,703.6,NaN,NaN,A,MIO_EUR,S1,D3REC_S212,BE
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1623.0,902.2,886.4,871.3,710.0,A,MIO_EUR,S1,D3REC_S212,BG
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,A,MIO_EUR,S1,D3REC_S212,CH
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.9,...,70.3,68.7,36.3,54.5,91.2,A,MIO_EUR,S1,D3REC_S212,CY

In [ ]:
#Reorganizamos la informacion
#Definimos cuales son las columnas de identificacion
columnas_id = ['freq', 'unit','sector','na_item', 'geo']